### ISSUE TITLE
Fix the larapack.io layout

### ISSUE THREAD

**Issue by bnku** [larapack/hooks#40]
I propose to fix css-styles to correctly display the hooks grid on larapack.io
```css
.hooks{
    display: flex;
    flex-wrap: wrap;
}
.hooks .hook .wrapper{
    padding-bottom: 50px;
}
```
